version: '3'

services:
  django:
    container_name: dj
    build:
      context: ./
      dockerfile: ./containers/development/Dockerfile
    command: /start.sh
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS=dev
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres